vich_uploader:
    db_driver: orm

    mappings:
        uploads:
            uri_prefix: /files/uploads
            upload_destination: '%kernel.project_dir%/public/files/uploads'
            inject_on_load: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid
